export interface Cocktail {
  id: string;
  name: string;
  emoji: string;
  ingredients: { name: string; amount: string; substitution?: string }[];
  instructions: string;
  flavor: { sweet: number; bitter: number; citrus: number; strong: number; smooth: number };
  mood: string[];
  spirit: string[];
  time: string[];
  effort: "Easy" | "Medium" | "Complex";
  reasoning: string;
}

export const cocktails: Cocktail[] = [
  {
    id: "margarita",
    name: "Classic Margarita",
    emoji: "🍋",
    ingredients: [
      { name: "Tequila", amount: "2 oz" },
      { name: "Lime juice", amount: "1 oz", substitution: "Lemon juice" },
      { name: "Triple sec", amount: "1 oz", substitution: "Cointreau or Grand Marnier" },
      { name: "Salt", amount: "for rim" },
    ],
    instructions: "Shake tequila, lime juice, and triple sec with ice. Strain into a salt-rimmed glass over fresh ice.",
    flavor: { sweet: 4, bitter: 2, citrus: 9, strong: 6, smooth: 5 },
    mood: ["Party", "Chill"],
    spirit: ["Tequila"],
    time: ["Day", "Night"],
    effort: "Easy",
    reasoning: "A timeless citrus-forward classic that balances tang and sweetness perfectly.",
  },
  {
    id: "old-fashioned",
    name: "Old Fashioned",
    emoji: "🥃",
    ingredients: [
      { name: "Bourbon", amount: "2 oz", substitution: "Rye whiskey" },
      { name: "Sugar cube", amount: "1", substitution: "Simple syrup (1/4 oz)" },
      { name: "Angostura bitters", amount: "2 dashes" },
      { name: "Orange peel", amount: "1 twist" },
    ],
    instructions: "Muddle sugar with bitters, add bourbon and ice, stir gently. Garnish with orange peel.",
    flavor: { sweet: 4, bitter: 5, citrus: 2, strong: 8, smooth: 7 },
    mood: ["Solo", "Fancy", "Date"],
    spirit: ["Whiskey"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "The quintessential whiskey cocktail — simple, sophisticated, and spirit-forward.",
  },
  {
    id: "mojito",
    name: "Mojito",
    emoji: "🌿",
    ingredients: [
      { name: "White rum", amount: "2 oz" },
      { name: "Lime juice", amount: "1 oz" },
      { name: "Sugar", amount: "2 tsp", substitution: "Simple syrup (1/2 oz)" },
      { name: "Mint leaves", amount: "6-8" },
      { name: "Soda water", amount: "Top" },
    ],
    instructions: "Muddle mint with sugar and lime juice. Add rum and ice, top with soda water. Stir gently.",
    flavor: { sweet: 6, bitter: 1, citrus: 7, strong: 4, smooth: 7 },
    mood: ["Chill", "Party"],
    spirit: ["Rum"],
    time: ["Day"],
    effort: "Medium",
    reasoning: "Refreshing and herbaceous — the perfect warm-weather crowd pleaser.",
  },
  {
    id: "espresso-martini",
    name: "Espresso Martini",
    emoji: "☕",
    ingredients: [
      { name: "Vodka", amount: "2 oz" },
      { name: "Coffee liqueur", amount: "1 oz", substitution: "Kahlúa" },
      { name: "Espresso", amount: "1 oz", substitution: "Strong cold brew" },
      { name: "Simple syrup", amount: "1/2 oz" },
    ],
    instructions: "Shake all ingredients vigorously with ice. Strain into a chilled coupe glass. Garnish with coffee beans.",
    flavor: { sweet: 5, bitter: 7, citrus: 0, strong: 6, smooth: 8 },
    mood: ["Date", "Fancy", "Party"],
    spirit: ["Vodka"],
    time: ["Night"],
    effort: "Medium",
    reasoning: "Bold, caffeinated elegance — a modern classic that energizes and impresses.",
  },
  {
    id: "cosmopolitan",
    name: "Cosmopolitan",
    emoji: "🍸",
    ingredients: [
      { name: "Vodka", amount: "1.5 oz", substitution: "Citrus vodka" },
      { name: "Triple sec", amount: "1 oz", substitution: "Cointreau" },
      { name: "Cranberry juice", amount: "1 oz" },
      { name: "Lime juice", amount: "1/2 oz" },
    ],
    instructions: "Shake all ingredients with ice. Strain into a chilled martini glass. Garnish with lime wheel.",
    flavor: { sweet: 6, bitter: 1, citrus: 7, strong: 5, smooth: 7 },
    mood: ["Party", "Date", "Fancy"],
    spirit: ["Vodka"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "Vibrant, balanced, and effortlessly chic — a cocktail that never goes out of style.",
  },
  {
    id: "whiskey-sour",
    name: "Whiskey Sour",
    emoji: "🍋",
    ingredients: [
      { name: "Bourbon", amount: "2 oz", substitution: "Rye whiskey" },
      { name: "Lemon juice", amount: "3/4 oz" },
      { name: "Simple syrup", amount: "1/2 oz" },
      { name: "Egg white", amount: "1 (optional)", substitution: "Aquafaba" },
    ],
    instructions: "Dry shake all ingredients without ice, then shake again with ice. Strain into a rocks glass. Garnish with cherry.",
    flavor: { sweet: 5, bitter: 3, citrus: 7, strong: 6, smooth: 6 },
    mood: ["Chill", "Solo", "Date"],
    spirit: ["Whiskey"],
    time: ["Night"],
    effort: "Medium",
    reasoning: "A beautifully balanced cocktail with a silky texture that showcases whiskey at its best.",
  },
  {
    id: "gin-tonic",
    name: "Gin & Tonic",
    emoji: "🫧",
    ingredients: [
      { name: "Gin", amount: "2 oz" },
      { name: "Tonic water", amount: "4 oz" },
      { name: "Lime wedge", amount: "1" },
    ],
    instructions: "Fill a glass with ice, add gin and tonic water. Stir gently and garnish with lime.",
    flavor: { sweet: 2, bitter: 6, citrus: 4, strong: 5, smooth: 6 },
    mood: ["Chill", "Solo"],
    spirit: ["Gin"],
    time: ["Day", "Night"],
    effort: "Easy",
    reasoning: "Effortless sophistication — botanical gin meets crisp tonic for a timeless pairing.",
  },
  {
    id: "negroni",
    name: "Negroni",
    emoji: "🔴",
    ingredients: [
      { name: "Gin", amount: "1 oz" },
      { name: "Campari", amount: "1 oz" },
      { name: "Sweet vermouth", amount: "1 oz" },
      { name: "Orange peel", amount: "1 twist" },
    ],
    instructions: "Stir all ingredients with ice. Strain into a rocks glass over fresh ice. Garnish with orange peel.",
    flavor: { sweet: 3, bitter: 9, citrus: 3, strong: 7, smooth: 5 },
    mood: ["Fancy", "Solo", "Date"],
    spirit: ["Gin"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "Bold and bittersweet — a perfectly balanced triptych of flavors for the adventurous palate.",
  },
  {
    id: "pina-colada",
    name: "Piña Colada",
    emoji: "🍍",
    ingredients: [
      { name: "White rum", amount: "2 oz" },
      { name: "Coconut cream", amount: "1.5 oz" },
      { name: "Pineapple juice", amount: "3 oz" },
    ],
    instructions: "Blend all ingredients with ice until smooth. Pour into a hurricane glass. Garnish with pineapple wedge.",
    flavor: { sweet: 9, bitter: 0, citrus: 3, strong: 3, smooth: 9 },
    mood: ["Chill", "Party"],
    spirit: ["Rum"],
    time: ["Day"],
    effort: "Medium",
    reasoning: "Tropical, creamy, and irresistibly smooth — pure vacation in a glass.",
  },
  {
    id: "moscow-mule",
    name: "Moscow Mule",
    emoji: "🫚",
    ingredients: [
      { name: "Vodka", amount: "2 oz" },
      { name: "Ginger beer", amount: "4 oz" },
      { name: "Lime juice", amount: "1/2 oz" },
      { name: "Lime wedge", amount: "1" },
    ],
    instructions: "Fill a copper mug with ice, add vodka and lime juice, top with ginger beer. Stir gently.",
    flavor: { sweet: 4, bitter: 2, citrus: 5, strong: 4, smooth: 6 },
    mood: ["Chill", "Party"],
    spirit: ["Vodka"],
    time: ["Day", "Night"],
    effort: "Easy",
    reasoning: "Crisp, spicy, and refreshing — the ginger kick makes this an instant crowd favorite.",
  },
  {
    id: "daiquiri",
    name: "Classic Daiquiri",
    emoji: "🌴",
    ingredients: [
      { name: "White rum", amount: "2 oz" },
      { name: "Lime juice", amount: "1 oz" },
      { name: "Simple syrup", amount: "3/4 oz" },
    ],
    instructions: "Shake all ingredients with ice. Strain into a chilled coupe glass.",
    flavor: { sweet: 5, bitter: 1, citrus: 8, strong: 5, smooth: 7 },
    mood: ["Chill", "Date"],
    spirit: ["Rum"],
    time: ["Day", "Night"],
    effort: "Easy",
    reasoning: "Deceptively simple, endlessly elegant — a perfectly balanced rum classic.",
  },
  {
    id: "manhattan",
    name: "Manhattan",
    emoji: "🏙️",
    ingredients: [
      { name: "Rye whiskey", amount: "2 oz", substitution: "Bourbon" },
      { name: "Sweet vermouth", amount: "1 oz" },
      { name: "Angostura bitters", amount: "2 dashes" },
      { name: "Maraschino cherry", amount: "1" },
    ],
    instructions: "Stir all ingredients with ice. Strain into a chilled coupe glass. Garnish with cherry.",
    flavor: { sweet: 5, bitter: 5, citrus: 1, strong: 8, smooth: 7 },
    mood: ["Fancy", "Date", "Solo"],
    spirit: ["Whiskey"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "Rich, complex, and deeply satisfying — the cocktail equivalent of a velvet suit.",
  },
  {
    id: "paloma",
    name: "Paloma",
    emoji: "🌸",
    ingredients: [
      { name: "Tequila", amount: "2 oz" },
      { name: "Grapefruit juice", amount: "3 oz", substitution: "Grapefruit soda (Squirt or Jarritos)" },
      { name: "Lime juice", amount: "1/2 oz" },
      { name: "Simple syrup", amount: "1/2 oz" },
      { name: "Soda water", amount: "Top" },
    ],
    instructions: "Combine tequila, grapefruit juice, lime juice, and syrup in a salt-rimmed glass over ice. Top with soda.",
    flavor: { sweet: 4, bitter: 4, citrus: 8, strong: 5, smooth: 6 },
    mood: ["Chill", "Party"],
    spirit: ["Tequila"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "Mexico's favorite tequila drink — more refreshing than a margarita, with beautiful grapefruit bitterness.",
  },
  {
    id: "aperol-spritz",
    name: "Aperol Spritz",
    emoji: "🧡",
    ingredients: [
      { name: "Aperol", amount: "2 oz" },
      { name: "Prosecco", amount: "3 oz" },
      { name: "Soda water", amount: "1 oz" },
      { name: "Orange slice", amount: "1" },
    ],
    instructions: "Fill a wine glass with ice. Add Aperol, prosecco, and soda water. Stir gently. Garnish with orange.",
    flavor: { sweet: 5, bitter: 6, citrus: 4, strong: 2, smooth: 8 },
    mood: ["Chill", "Date", "Fancy"],
    spirit: ["None"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "Light, bubbly, and effortlessly glamorous — the golden hour drink.",
  },
  {
    id: "mai-tai",
    name: "Mai Tai",
    emoji: "🌺",
    ingredients: [
      { name: "White rum", amount: "1 oz" },
      { name: "Dark rum", amount: "1 oz" },
      { name: "Orange curaçao", amount: "1 oz", substitution: "Triple sec" },
      { name: "Lime juice", amount: "1 oz" },
      { name: "Orgeat syrup", amount: "1/2 oz", substitution: "Amaretto (1/4 oz)" },
    ],
    instructions: "Shake all ingredients with ice. Strain into a glass filled with crushed ice. Garnish with mint and lime.",
    flavor: { sweet: 7, bitter: 2, citrus: 6, strong: 6, smooth: 6 },
    mood: ["Party", "Chill"],
    spirit: ["Rum"],
    time: ["Day", "Night"],
    effort: "Complex",
    reasoning: "Tropical layered complexity — the Polynesian masterpiece that launched tiki culture.",
  },
  {
    id: "french-75",
    name: "French 75",
    emoji: "🥂",
    ingredients: [
      { name: "Gin", amount: "1 oz", substitution: "Cognac" },
      { name: "Lemon juice", amount: "1/2 oz" },
      { name: "Simple syrup", amount: "1/2 oz" },
      { name: "Champagne", amount: "Top", substitution: "Prosecco or sparkling wine" },
    ],
    instructions: "Shake gin, lemon juice, and syrup with ice. Strain into a champagne flute. Top with champagne.",
    flavor: { sweet: 5, bitter: 2, citrus: 6, strong: 5, smooth: 8 },
    mood: ["Fancy", "Date", "Party"],
    spirit: ["Gin"],
    time: ["Night"],
    effort: "Medium",
    reasoning: "Sparkling elegance with a citrus backbone — the champagne cocktail that makes every moment special.",
  },
  {
    id: "dark-stormy",
    name: "Dark 'n' Stormy",
    emoji: "⛈️",
    ingredients: [
      { name: "Dark rum", amount: "2 oz" },
      { name: "Ginger beer", amount: "4 oz" },
      { name: "Lime juice", amount: "1/2 oz" },
    ],
    instructions: "Fill a glass with ice. Add ginger beer, then float dark rum on top. Squeeze lime.",
    flavor: { sweet: 4, bitter: 3, citrus: 3, strong: 5, smooth: 5 },
    mood: ["Chill", "Solo"],
    spirit: ["Rum"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "Bold and stormy — dark rum meets fiery ginger for a dramatically simple drink.",
  },
  {
    id: "martini",
    name: "Classic Martini",
    emoji: "🍸",
    ingredients: [
      { name: "Gin", amount: "2.5 oz", substitution: "Vodka" },
      { name: "Dry vermouth", amount: "1/2 oz" },
      { name: "Olive or lemon twist", amount: "for garnish" },
    ],
    instructions: "Stir gin and vermouth with ice. Strain into a chilled martini glass. Garnish with olive or lemon twist.",
    flavor: { sweet: 1, bitter: 4, citrus: 2, strong: 9, smooth: 7 },
    mood: ["Fancy", "Date", "Solo"],
    spirit: ["Gin"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "The pinnacle of cocktail minimalism — pure, potent, and impossibly sophisticated.",
  },
  {
    id: "tom-collins",
    name: "Tom Collins",
    emoji: "🍋",
    ingredients: [
      { name: "Gin", amount: "2 oz" },
      { name: "Lemon juice", amount: "1 oz" },
      { name: "Simple syrup", amount: "1/2 oz" },
      { name: "Soda water", amount: "Top" },
    ],
    instructions: "Shake gin, lemon juice, and syrup with ice. Strain into a tall glass with ice. Top with soda water.",
    flavor: { sweet: 4, bitter: 2, citrus: 7, strong: 4, smooth: 7 },
    mood: ["Chill", "Solo"],
    spirit: ["Gin"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "A tall, refreshing classic — like lemonade for grown-ups with botanical flair.",
  },
  {
    id: "tequila-sunrise",
    name: "Tequila Sunrise",
    emoji: "🌅",
    ingredients: [
      { name: "Tequila", amount: "2 oz" },
      { name: "Orange juice", amount: "4 oz" },
      { name: "Grenadine", amount: "1/2 oz" },
    ],
    instructions: "Fill a glass with ice, add tequila and orange juice. Slowly pour grenadine down the side. Don't stir.",
    flavor: { sweet: 7, bitter: 1, citrus: 7, strong: 4, smooth: 7 },
    mood: ["Chill", "Party"],
    spirit: ["Tequila"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "A sunrise in a glass — sweet, citrusy, and visually stunning with that iconic gradient.",
  },
  {
    id: "sidecar",
    name: "Sidecar",
    emoji: "🏍️",
    ingredients: [
      { name: "Cognac", amount: "2 oz", substitution: "Brandy" },
      { name: "Triple sec", amount: "1 oz", substitution: "Cointreau" },
      { name: "Lemon juice", amount: "3/4 oz" },
    ],
    instructions: "Shake all ingredients with ice. Strain into a sugar-rimmed coupe glass.",
    flavor: { sweet: 4, bitter: 3, citrus: 6, strong: 7, smooth: 7 },
    mood: ["Fancy", "Date"],
    spirit: ["None"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "Refined and velvety — cognac and citrus in perfect harmony for the discerning drinker.",
  },
  {
    id: "vodka-soda",
    name: "Vodka Soda",
    emoji: "💧",
    ingredients: [
      { name: "Vodka", amount: "2 oz" },
      { name: "Soda water", amount: "4 oz" },
      { name: "Lime wedge", amount: "1" },
    ],
    instructions: "Fill a glass with ice. Add vodka and soda water. Squeeze lime and drop it in.",
    flavor: { sweet: 1, bitter: 0, citrus: 3, strong: 4, smooth: 8 },
    mood: ["Chill", "Solo"],
    spirit: ["Vodka"],
    time: ["Day", "Night"],
    effort: "Easy",
    reasoning: "Clean, crisp, and zero fuss — the go-to for letting the spirit speak.",
  },
  {
    id: "amaretto-sour",
    name: "Amaretto Sour",
    emoji: "🍑",
    ingredients: [
      { name: "Amaretto", amount: "1.5 oz" },
      { name: "Bourbon", amount: "3/4 oz" },
      { name: "Lemon juice", amount: "1 oz" },
      { name: "Simple syrup", amount: "1/2 oz" },
      { name: "Egg white", amount: "1", substitution: "Aquafaba" },
    ],
    instructions: "Dry shake all ingredients, then shake with ice. Strain into a rocks glass. Garnish with cherry.",
    flavor: { sweet: 7, bitter: 2, citrus: 5, strong: 4, smooth: 8 },
    mood: ["Date", "Chill"],
    spirit: ["Whiskey"],
    time: ["Night"],
    effort: "Medium",
    reasoning: "Nutty, sweet, and silky — a dessert-like cocktail with surprising depth.",
  },
  {
    id: "caipirinha",
    name: "Caipirinha",
    emoji: "🇧🇷",
    ingredients: [
      { name: "Cachaça", amount: "2 oz", substitution: "White rum" },
      { name: "Lime", amount: "1, cut into wedges" },
      { name: "Sugar", amount: "2 tsp" },
    ],
    instructions: "Muddle lime wedges and sugar in a glass. Fill with ice, add cachaça. Stir well.",
    flavor: { sweet: 5, bitter: 1, citrus: 9, strong: 6, smooth: 4 },
    mood: ["Party", "Chill"],
    spirit: ["Rum"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "Brazil's national cocktail — raw, vibrant, and bursting with fresh lime energy.",
  },
  {
    id: "irish-coffee",
    name: "Irish Coffee",
    emoji: "☘️",
    ingredients: [
      { name: "Irish whiskey", amount: "1.5 oz" },
      { name: "Hot coffee", amount: "6 oz" },
      { name: "Brown sugar", amount: "1 tsp" },
      { name: "Heavy cream", amount: "Lightly whipped, floated" },
    ],
    instructions: "Dissolve sugar in hot coffee. Add whiskey. Float lightly whipped cream on top. Don't stir.",
    flavor: { sweet: 5, bitter: 6, citrus: 0, strong: 5, smooth: 8 },
    mood: ["Solo", "Chill"],
    spirit: ["Whiskey"],
    time: ["Day", "Night"],
    effort: "Medium",
    reasoning: "Warm, comforting, and indulgent — the perfect cocktail for when you need both warmth and spirit.",
  },
  {
    id: "long-island",
    name: "Long Island Iced Tea",
    emoji: "🏝️",
    ingredients: [
      { name: "Vodka", amount: "1/2 oz" },
      { name: "Gin", amount: "1/2 oz" },
      { name: "Rum", amount: "1/2 oz" },
      { name: "Tequila", amount: "1/2 oz" },
      { name: "Triple sec", amount: "1/2 oz" },
      { name: "Lemon juice", amount: "1 oz" },
      { name: "Cola", amount: "Top" },
    ],
    instructions: "Combine all spirits and lemon juice in a tall glass with ice. Top with cola. Garnish with lemon.",
    flavor: { sweet: 5, bitter: 2, citrus: 5, strong: 9, smooth: 4 },
    mood: ["Party"],
    spirit: ["Vodka", "Gin", "Rum", "Tequila"],
    time: ["Night"],
    effort: "Medium",
    reasoning: "The ultimate party powerhouse — deceptively smooth for its formidable strength.",
  },
  {
    id: "bellini",
    name: "Bellini",
    emoji: "🍑",
    ingredients: [
      { name: "Prosecco", amount: "4 oz" },
      { name: "Peach purée", amount: "2 oz", substitution: "Peach nectar" },
    ],
    instructions: "Pour peach purée into a champagne flute. Slowly top with prosecco. Stir gently.",
    flavor: { sweet: 7, bitter: 1, citrus: 2, strong: 2, smooth: 9 },
    mood: ["Fancy", "Date", "Chill"],
    spirit: ["None"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "Venetian elegance in a flute — delicate peach meets sparkling wine for pure sophistication.",
  },
  {
    id: "sazerac",
    name: "Sazerac",
    emoji: "⚜️",
    ingredients: [
      { name: "Rye whiskey", amount: "2 oz", substitution: "Cognac" },
      { name: "Sugar cube", amount: "1" },
      { name: "Peychaud's bitters", amount: "3 dashes" },
      { name: "Absinthe", amount: "Rinse", substitution: "Herbsaint or Pernod" },
      { name: "Lemon peel", amount: "1 twist" },
    ],
    instructions: "Rinse a chilled glass with absinthe. Muddle sugar with bitters, add whiskey and ice, stir. Strain into the absinthe-rinsed glass.",
    flavor: { sweet: 3, bitter: 7, citrus: 2, strong: 8, smooth: 6 },
    mood: ["Fancy", "Solo"],
    spirit: ["Whiskey"],
    time: ["Night"],
    effort: "Complex",
    reasoning: "New Orleans royalty — complex, aromatic, and steeped in 200 years of cocktail history.",
  },
  {
    id: "mint-julep",
    name: "Mint Julep",
    emoji: "🐴",
    ingredients: [
      { name: "Bourbon", amount: "2.5 oz" },
      { name: "Simple syrup", amount: "1/2 oz" },
      { name: "Mint leaves", amount: "8-10" },
    ],
    instructions: "Muddle mint with simple syrup. Add bourbon and crushed ice. Stir until glass frosts. Top with more crushed ice.",
    flavor: { sweet: 5, bitter: 2, citrus: 0, strong: 7, smooth: 6 },
    mood: ["Fancy", "Chill"],
    spirit: ["Whiskey"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "Southern charm in crushed ice — minty, bourbon-forward, and eternally refreshing.",
  },
  {
    id: "bloody-mary",
    name: "Bloody Mary",
    emoji: "🍅",
    ingredients: [
      { name: "Vodka", amount: "2 oz" },
      { name: "Tomato juice", amount: "4 oz" },
      { name: "Lemon juice", amount: "1/2 oz" },
      { name: "Worcestershire sauce", amount: "2 dashes" },
      { name: "Hot sauce", amount: "2 dashes" },
      { name: "Salt and pepper", amount: "To taste" },
      { name: "Celery stalk", amount: "1" },
    ],
    instructions: "Combine all ingredients in a glass with ice. Stir well. Garnish with celery, olive, and lemon.",
    flavor: { sweet: 2, bitter: 3, citrus: 4, strong: 4, smooth: 3 },
    mood: ["Chill", "Solo"],
    spirit: ["Vodka"],
    time: ["Day"],
    effort: "Medium",
    reasoning: "The savory cocktail icon — spicy, tangy, and the undisputed brunch champion.",
  },
  {
    id: "gimlet",
    name: "Gimlet",
    emoji: "💚",
    ingredients: [
      { name: "Gin", amount: "2 oz", substitution: "Vodka" },
      { name: "Lime juice", amount: "3/4 oz" },
      { name: "Simple syrup", amount: "3/4 oz" },
    ],
    instructions: "Shake all ingredients with ice. Strain into a chilled coupe glass. Garnish with lime wheel.",
    flavor: { sweet: 5, bitter: 2, citrus: 8, strong: 6, smooth: 7 },
    mood: ["Date", "Fancy"],
    spirit: ["Gin"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "Crisp, tart, and beautifully minimal — gin and lime in their purest, most elegant form.",
  },
  {
    id: "hurricane",
    name: "Hurricane",
    emoji: "🌀",
    ingredients: [
      { name: "Dark rum", amount: "2 oz" },
      { name: "White rum", amount: "2 oz" },
      { name: "Passion fruit juice", amount: "2 oz", substitution: "Orange juice" },
      { name: "Orange juice", amount: "1 oz" },
      { name: "Lime juice", amount: "1/2 oz" },
      { name: "Grenadine", amount: "1 oz" },
    ],
    instructions: "Shake all ingredients with ice. Strain into a hurricane glass filled with ice.",
    flavor: { sweet: 8, bitter: 1, citrus: 6, strong: 6, smooth: 5 },
    mood: ["Party"],
    spirit: ["Rum"],
    time: ["Night"],
    effort: "Medium",
    reasoning: "A New Orleans party in a glass — fruity, potent, and impossible to have just one.",
  },
  {
    id: "white-russian",
    name: "White Russian",
    emoji: "🥛",
    ingredients: [
      { name: "Vodka", amount: "2 oz" },
      { name: "Coffee liqueur", amount: "1 oz", substitution: "Kahlúa" },
      { name: "Heavy cream", amount: "1 oz", substitution: "Milk or oat milk" },
    ],
    instructions: "Pour vodka and coffee liqueur over ice. Float cream on top. Stir if desired.",
    flavor: { sweet: 7, bitter: 4, citrus: 0, strong: 5, smooth: 9 },
    mood: ["Chill", "Solo"],
    spirit: ["Vodka"],
    time: ["Night"],
    effort: "Easy",
    reasoning: "Creamy, rich, and effortlessly cool — the Dude abides, and so will you.",
  },
  {
    id: "aviation",
    name: "Aviation",
    emoji: "✈️",
    ingredients: [
      { name: "Gin", amount: "2 oz" },
      { name: "Maraschino liqueur", amount: "1/2 oz" },
      { name: "Crème de violette", amount: "1/4 oz" },
      { name: "Lemon juice", amount: "3/4 oz" },
    ],
    instructions: "Shake all ingredients with ice. Strain into a chilled coupe glass. Garnish with cherry.",
    flavor: { sweet: 4, bitter: 3, citrus: 6, strong: 6, smooth: 7 },
    mood: ["Fancy", "Date"],
    spirit: ["Gin"],
    time: ["Night"],
    effort: "Complex",
    reasoning: "A stunning violet-hued classic — floral, delicate, and impossibly photogenic.",
  },
  {
    id: "penicillin",
    name: "Penicillin",
    emoji: "💊",
    ingredients: [
      { name: "Blended scotch", amount: "2 oz" },
      { name: "Lemon juice", amount: "3/4 oz" },
      { name: "Honey-ginger syrup", amount: "3/4 oz", substitution: "Honey syrup + grated ginger" },
      { name: "Islay scotch", amount: "Float (1/4 oz)", substitution: "Skip if unavailable" },
    ],
    instructions: "Shake blended scotch, lemon juice, and syrup with ice. Strain over fresh ice. Float Islay scotch on top.",
    flavor: { sweet: 4, bitter: 4, citrus: 6, strong: 7, smooth: 5 },
    mood: ["Fancy", "Solo"],
    spirit: ["Whiskey"],
    time: ["Night"],
    effort: "Complex",
    reasoning: "A modern classic — smoky, spicy, and medicinal in the best possible way.",
  },
  {
    id: "rum-punch",
    name: "Rum Punch",
    emoji: "🎉",
    ingredients: [
      { name: "Dark rum", amount: "2 oz" },
      { name: "Orange juice", amount: "2 oz" },
      { name: "Pineapple juice", amount: "2 oz" },
      { name: "Lime juice", amount: "1 oz" },
      { name: "Grenadine", amount: "1/2 oz" },
      { name: "Nutmeg", amount: "Pinch on top" },
    ],
    instructions: "Shake all ingredients with ice. Pour into a tall glass. Garnish with nutmeg and fruit.",
    flavor: { sweet: 8, bitter: 1, citrus: 6, strong: 5, smooth: 6 },
    mood: ["Party", "Chill"],
    spirit: ["Rum"],
    time: ["Day", "Night"],
    effort: "Easy",
    reasoning: "Caribbean sunshine in a glass — fruity, festive, and made for sharing.",
  },
  {
    id: "bramble",
    name: "Bramble",
    emoji: "🫐",
    ingredients: [
      { name: "Gin", amount: "2 oz" },
      { name: "Lemon juice", amount: "1 oz" },
      { name: "Simple syrup", amount: "1/2 oz" },
      { name: "Crème de mûre", amount: "1/2 oz", substitution: "Chambord or blackberry liqueur" },
    ],
    instructions: "Shake gin, lemon, and syrup with ice. Strain over crushed ice. Drizzle crème de mûre on top.",
    flavor: { sweet: 6, bitter: 2, citrus: 7, strong: 5, smooth: 6 },
    mood: ["Date", "Fancy"],
    spirit: ["Gin"],
    time: ["Day", "Night"],
    effort: "Medium",
    reasoning: "A berry-laced gin sour — gorgeous, fruity, and perfect for impressing someone special.",
  },
  {
    id: "virgin-mojito",
    name: "Virgin Mojito",
    emoji: "🌱",
    ingredients: [
      { name: "Lime juice", amount: "1 oz" },
      { name: "Sugar", amount: "2 tsp" },
      { name: "Mint leaves", amount: "6-8" },
      { name: "Soda water", amount: "Top" },
    ],
    instructions: "Muddle mint with sugar and lime juice. Add ice and top with soda water. Stir gently.",
    flavor: { sweet: 6, bitter: 0, citrus: 7, strong: 0, smooth: 8 },
    mood: ["Chill", "Solo"],
    spirit: ["None"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "All the freshness, none of the alcohol — a beautiful mocktail everyone can enjoy.",
  },
  {
    id: "shirley-temple",
    name: "Shirley Temple",
    emoji: "🍒",
    ingredients: [
      { name: "Ginger ale", amount: "6 oz", substitution: "Lemon-lime soda" },
      { name: "Grenadine", amount: "1 oz" },
      { name: "Maraschino cherry", amount: "2-3" },
      { name: "Orange slice", amount: "1" },
    ],
    instructions: "Fill a glass with ice. Add ginger ale and grenadine. Stir gently. Garnish with cherries and orange.",
    flavor: { sweet: 9, bitter: 0, citrus: 3, strong: 0, smooth: 9 },
    mood: ["Chill", "Party"],
    spirit: ["None"],
    time: ["Day"],
    effort: "Easy",
    reasoning: "Nostalgic, sweet, and universally loved — the most elegant non-alcoholic classic.",
  },
];
